name: Main CI

on:
  push:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deployment
        uses: fifsky/ssh-action@master
        with:
          command: |
            whoami
            echo "$HOST"
            ls -a
          host: ${{ secrets.MAIN_HOST }} 
          user: ${{ secrets.MAIN_USERNAME }} 
          key: ${{ secrets.MAIN_KEY }}
          port: ${{ secrets.PORT }} 

