name: Main CI

on:
  push:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MAIN_HOST }}
          key: ${{ secrets.MAIN_KEY }}
          passphrase: ${{ secrets.MAIN_PASSPHRASE }}
          username: ${{ secrets.MAIN_USERNAME }}
          script: |
            cd /var/www/beanicki
            git pull origin main
            composer install
            npm install
            php artisan migrate
            npm run build
            php artisan optimize:clear
